### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by mitchcecg** [se1exin/ESPBlinds#1]
when I compile with Arduino ide 1.9 I get the following errors
can you supply info on compiling the code
THANX
MITCH
If I had a son he would be a son of a Mitch
-----
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void setup()':
ESPBlinds:64:3: error: 'setupWifi' was not declared in this scope
   64 |   setupWifi();
      |   ^~~~~~~~~
ESPBlinds:66:26: error: 'mqttCallback' was not declared in this scope
   66 |   mqttClient.setCallback(mqttCallback);
      |                          ^~~~~~~~~~~~
ESPBlinds:68:5: error: 'mqttReconnect' was not declared in this scope
   68 |     mqttReconnect();
      |     ^~~~~~~~~~~~~
ESPBlinds:71:3: error: 'mqttPublish' was not declared in this scope
   71 |   mqttPublish(MQTT_TOPIC_ENABLED, 0);
      |   ^~~~~~~~~~~
ESPBlinds:74:3: error: 'loadFromEeprom' was not declared in this scope
   74 |   loadFromEeprom();
      |   ^~~~~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void loop()':
ESPBlinds:96:5: error: 'mqttReconnect' was not declared in this scope
   96 |     mqttReconnect();
      |     ^~~~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void closeBlinds()':
ESPBlinds:104:3: error: 'mqttPublish' was not declared in this scope
  104 |   mqttPublish(MQTT_TOPIC_STATE, "closing");
      |   ^~~~~~~~~~~
ESPBlinds:105:3: error: 'setStepperDirection' was not declared in this scope; did you mean 'stepDirection'?
  105 |   setStepperDirection(DIRECTION_CLOSE);
      |   ^~~~~~~~~~~~~~~~~~~
      |   stepDirection
ESPBlinds:106:3: error: 'setStepperMode' was not declared in this scope
  106 |   setStepperMode(MODE_CLOSE);
      |   ^~~~~~~~~~~~~~
ESPBlinds:107:3: error: 'stepFor' was not declared in this scope; did you mean 'stepper'?
  107 |   stepFor(STEPS_VERTICAL);
      |   ^~~~~~~
      |   stepper
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void openBlinds()':
ESPBlinds:114:3: error: 'mqttPublish' was not declared in this scope
  114 |   mqttPublish(MQTT_TOPIC_STATE, "opening");
      |   ^~~~~~~~~~~
ESPBlinds:115:3: error: 'setStepperDirection' was not declared in this scope; did you mean 'stepDirection'?
  115 |   setStepperDirection(DIRECTION_OPEN);
      |   ^~~~~~~~~~~~~~~~~~~
      |   stepDirection
ESPBlinds:116:3: error: 'setStepperMode' was not declared in this scope
  116 |   setStepperMode(MODE_OPEN);
      |   ^~~~~~~~~~~~~~
ESPBlinds:117:3: error: 'stepFor' was not declared in this scope; did you mean 'stepper'?
  117 |   stepFor(STEPS_VERTICAL);
      |   ^~~~~~~
      |   stepper
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void stepFor(int)':
ESPBlinds:127:3: error: 'setStepperEnabled' was not declared in this scope; did you mean 'stepperEnabled'?
  127 |   setStepperEnabled(true);
      |   ^~~~~~~~~~~~~~~~~
      |   stepperEnabled
ESPBlinds:152:9: error: 'mqttPublish' was not declared in this scope
  152 |         mqttPublish(MQTT_TOPIC_STEPS, currentStep);
      |         ^~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void setStepperMode(int)':
ESPBlinds:163:3: error: 'mqttPublish' was not declared in this scope
  163 |   mqttPublish(MQTT_TOPIC_MODE, mode);
      |   ^~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void setStepperEnabled(bool)':
ESPBlinds:171:5: error: 'mqttPublish' was not declared in this scope
  171 |     mqttPublish(MQTT_TOPIC_ENABLED, 1);
      |     ^~~~~~~~~~~
ESPBlinds:174:5: error: 'mqttPublish' was not declared in this scope
  174 |     mqttPublish(MQTT_TOPIC_ENABLED, 0);
      |     ^~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void setStepperDirection(int)':
ESPBlinds:184:5: error: 'mqttPublish' was not declared in this scope
  184 |     mqttPublish(MQTT_TOPIC_DIRECTION, "forwards");
      |     ^~~~~~~~~~~
ESPBlinds:187:5: error: 'mqttPublish' was not declared in this scope
  187 |     mqttPublish(MQTT_TOPIC_DIRECTION, "reverse");
      |     ^~~~~~~~~~~
B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void mqttCallback(char*, byte*, unsigned int)':
ESPBlinds:257:5: error: 'saveToEeprom' was not declared in this scope
  257 |     saveToEeprom();
      |     ^~~~~~~~~~~~
ESPBlinds:261:5: error: 'saveToEeprom' was not declared in this scope
  261 |     saveToEeprom();
      |     ^~~~~~~~~~~~
ESPBlinds:265:5: error: 'saveToEeprom' was not declared in this scope
  265 |     saveToEeprom();
      |     ^~~~~~~~~~~~
ESPBlinds:269:5: error: 'saveToEeprom' was not declared in this scope
  269 |     saveToEeprom();
      |     ^~~~~~~~~~~~
ESPBlinds:273:5: error: 'saveToEeprom' was not declared in this scope
  273 |     saveToEeprom();
      |     ^~~~~~~~~~~~
exit status 1
'setupWifi' was not declared in this scope
I

**Comment by se1exin** [comment]
Ha wow, that's quite the error.. Did you copy `constants.example.h` to `constants.h` and fill out the Wifi & MQTT details (sorry, I acknowledge this was not documented at all in the readme).

Also, the `.ino` sketch has ESP8266 includes, are using an ESP8266 board?

Finally, the following arduino library needs to be installed:
- https://github.com/knolleary/pubsubclient

(I really wish the Ardiuno IDE had a project package management solution)

Again, I acknowledge that none of the above has been documented at all in the readme or otherwise - sorry about that.

**Comment by mitchcecg** [comment]
Thanks for the response  
Yes I did copy constants.example.h to constants.hand edited it
I have now installed the library 
I am still getting the same error

**Comment by se1exin** [comment]
That's really odd that are you are still getting errors. Can you please try moving the `setup()` and `loop()` functions to the end of the file?

Also just noticed you mention you are using Arduino IDE 1.9 which appears to be a beta version. I am successfully compiling this using Arduino IDE 1.8.19 (on linux) - can you try using version 1.8.19?

**Comment by mitchcecg** [comment]
My friend Eric is a programmer and he did not have time to solve the issues but he pointed out that the definitions shown here and others are not set up in the code.
I am not a programmer so this is the best explanation I can give you


// Locals
int currentStep = 0;
int currentMode = MODE_OPEN;
int stepDirection = EASYDRIVER_DIRECTION_FORWARDS;
bool stepperEnabled = true;
bool isOpening = false;
bool isClosing = false;
void setupWifi(void);
void mqttCallback(char* topic, byte* payload, unsigned int length) ;

[CECG_trans_Logo]THANX
Mitch Geier
President
Computer Emergency & Consulting Group, LLC.
***@***.******@***.***>
609-758-1111 Ext 1

Privileged-Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer do not consent to Internet email for messages of this kind.

The sender believes that this E-mail and any attachments were free of any virus, worm, Trojan horse, and/or malicious code when sent. This message and its attachments could have been infected during  transmission. By reading the message and opening any attachments, the recipient accepts full responsibility for taking protective and remedial action about viruses and other defects. CECG LLC. and Mitch Geier are not liable for any loss or damage arising in any way from this message or its attachments.
P Please consider the environment before printing this email.

**Comment by mitchcecg** [comment]
Ok I have done the decorations my buddy told me to do to  the code I have from github. It solved most of the errrors. However,  he states the code I have could  never work. So I might have a bad set of files from  github. Or github  was not updated with the latest…
here is why

I am getting this error

B:\Blinds\ESPBlinds\ESPBlinds.ino: In function 'void setup()':
ESPBlinds:81:47: error: invalid conversion from 'const char*' to 'int' [-fpermissive]
   81 |   mqttPublish(MQTT_TOPIC_STATE, "closed");

You are defining

void mqttPublish(char *topic, int payload) {
  // Serial.print(topic);
  // Serial.print(": ");
  // Serial.println(payload);

But the payload is not an int
As shown here
  mqttPublish(MQTT_TOPIC_DIRECTION, "reverse");


so Please if you have a version that compiles please let me know where I can get it




[CECG_trans_Logo]THANX
Mitch Geier
President
Computer Emergency & Consulting Group, LLC.
***@***.******@***.***>
609-758-1111 Ext 1

Privileged-Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer do not consent to Internet email for messages of this kind.

The sender believes that this E-mail and any attachments were free of any virus, worm, Trojan horse, and/or malicious code when sent. This message and its attachments could have been infected during  transmission. By reading the message and opening any attachments, the recipient accepts full responsibility for taking protective and remedial action about viruses and other defects. CECG LLC. and Mitch Geier are not liable for any loss or damage arising in any way from this message or its attachments.
P Please consider the environment before printing this email.

**Comment by mitchcecg** [comment]
After further examination you have 2 functions with the same name mqqtPublish that are slightly different.
Since I am not a coder I have made changes that might work . At least with these changes it compiles. Here is the entire file in text.

Let me know what I might be missing per my last email…And thanks for the help and project

===========================
#include <ESP8266WiFi.h>
#include <EEPROM.h>
#include <PubSubClient.h>
#include "constants.h"
#include "EasyDriver.h"

// Outputs
const int PIN_STEP = 4;
const int PIN_DIR = 5;
const int PIN_MS1 = -1;
const int PIN_MS2 = -1;
const int PIN_ENABLE = 14;
const int PIN_FAN = 13;

// Inputs
//const int PIN_CUTOFF_CLOSE = 0;
//const int PIN_CUTOFF_OPEN = 3;

EasyDriver stepper = EasyDriver(PIN_STEP, PIN_DIR, PIN_MS1, PIN_MS2, PIN_ENABLE);

WiFiClient espClient;
PubSubClient mqttClient(espClient);

// Down = forwards == close
// Up   = Reverse == open
const int DIRECTION_CLOSE = EASYDRIVER_DIRECTION_FORWARDS;
const int DIRECTION_OPEN = EASYDRIVER_DIRECTION_REVERSE;

const bool MQTT_SEND_STEPS = false;

// Vars that are updatable via MQTT and saved into EEPROM...

// If this number is not found in EEPROM, then we assume no EEPROM values exist/have been saved
// and all other EEPROM values should be discarded/fallback to default values.
// See loadFromEeprom()
int EEPROM_MAGIC_NUMBER = 10001;
int STEPS_VERTICAL = 15000; // Number of full steps required to complete open/close sequence

int DELAY_CLOSE = 500; // In micros
int MODE_CLOSE = EASYDRIVER_MODE_FULL_STEP;

int DELAY_OPEN = 500; // In micros
int MODE_OPEN = EASYDRIVER_MODE_FULL_STEP;

// Locals
int currentStep = 0;
int currentMode = MODE_OPEN;
int stepDirection = EASYDRIVER_DIRECTION_FORWARDS;
bool stepperEnabled = true;
bool isOpening = false;
bool isClosing = false;
void setupWifi(void);
void mqttCallback(char* topic, byte* payload, unsigned int length) ;
void mqttReconnect(void);
void loadFromEeprom(void);
void setStepperDirection(int direction);
void setStepperMode(int mode);
void stepFor(int steps);
void setStepperEnabled(bool enabled);
void saveToEeprom();
void mqttPublish1(char *topic, int payload);
void mqttPublish(char *topic, String payload);
void setup() {
  // Cut off switches (not used in hardware, but implemented in case required in future)
//  pinMode(PIN_CUTOFF_CLOSE, INPUT_PULLUP);
//  pinMode(PIN_CUTOFF_OPEN, INPUT_PULLUP);
  pinMode(PIN_FAN, OUTPUT);

  stepper.reset();

  Serial.begin(115200);
  while (! Serial);

  setupWifi();
  mqttClient.setServer(MQTT_SERVER, 1883);
  mqttClient.setCallback(mqttCallback);
  if (!mqttClient.connected()) {
    mqttReconnect();
  }

  mqttPublish1(MQTT_TOPIC_ENABLED, 0);
  mqttPublish(MQTT_TOPIC_STATE, "closed");
  mqttPublish1(MQTT_TOPIC_STEPS, currentStep);
  loadFromEeprom();

  // Topic for controlling the stepper remotely
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_ENABLED);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_DIRECTION);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_STEPFOR);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_BLINDS);

  // Topics for updating EEPROM values remotely
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_MODE_OPEN);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_MODE_CLOSE);
 mqttClient.subscribe(MQTT_TOPIC_CONTROL_DELAY_OPEN);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_DELAY_CLOSE);
  mqttClient.subscribe(MQTT_TOPIC_CONTROL_STEPS_VERTICAL);
}


/**
* MAIN LOOP
*/
void loop() {
  if (!mqttClient.connected()) {
    mqttReconnect();
  }
  mqttClient.loop();
}


void closeBlinds() {
  isClosing = true;
  mqttPublish(MQTT_TOPIC_STATE, "closing");
  setStepperDirection(DIRECTION_CLOSE);
  setStepperMode(MODE_CLOSE);
  stepFor(STEPS_VERTICAL);
  mqttPublish(MQTT_TOPIC_STATE, "closed");
  isClosing = false;
}

void openBlinds() {
  isOpening = true;
  mqttPublish(MQTT_TOPIC_STATE, "opening");
  setStepperDirection(DIRECTION_OPEN);
  setStepperMode(MODE_OPEN);
  stepFor(STEPS_VERTICAL);
  mqttPublish(MQTT_TOPIC_STATE, "opened");
  isOpening = false;
}


/**
* STEPPER WRAPPERS
*/
void stepFor(int steps) {
  setStepperEnabled(true);
  for (int i = 0; i < steps; i++) {
//    Serial.print("STEP");
//    Serial.println(i);
    // Stepping mode is effectively a multiplier on the desired number of steps
    // E.g. a quarter step mode, to achieve a full step we need to do 4x stepper steps
    for (int x = 0; x < currentMode; x++) {
      stepper.step();
    }

    currentStep += stepDirection;
//    if (stepDirection == DIRECTION_CLOSE && digitalRead(PIN_CUTOFF_CLOSE) == LOW) {
//      Serial.println("ABORT CLOSE");
//      break;
//    }
//    if (stepDirection == DIRECTION_OPEN && digitalRead(PIN_CUTOFF_OPEN) == LOW) {
//      Serial.println("ABORT OPEN");
//      break;
//    }
    if (!stepperEnabled) {
      break;
    }

    if (MQTT_SEND_STEPS) {
      if (currentStep % 250 == 0) {
        mqttPublish1(MQTT_TOPIC_STEPS, currentStep);
      }
    }
    mqttClient.loop();
  }
  setStepperEnabled(false);
}

void setStepperMode(int mode) {
  stepper.setMode(mode);
  currentMode = mode;
  mqttPublish1(MQTT_TOPIC_MODE, mode);
}

void setStepperEnabled(bool enabled) {
  stepper.enable(enabled);

  if (enabled) {
    digitalWrite(PIN_FAN, HIGH);
    mqttPublish1(MQTT_TOPIC_ENABLED, 1);
  } else {
    digitalWrite(PIN_FAN, LOW);
    mqttPublish1(MQTT_TOPIC_ENABLED, 0);
  }
  stepperEnabled = enabled;
}

void setStepperDirection(int direction) {
  stepper.setDirection(direction);
  stepDirection = direction;
  if (direction == EASYDRIVER_DIRECTION_FORWARDS) {
    stepper.setDelay(DELAY_CLOSE);
    mqttPublish(MQTT_TOPIC_DIRECTION, "forwards");
  } else {
    stepper.setDelay(DELAY_OPEN);
    mqttPublish(MQTT_TOPIC_DIRECTION, "reverse");
  }
}


/**
* WIFI / MQTT HELPERS
*/
void setupWifi() {
  Serial.print("Connecting to ");
  Serial.println(WIFI_SSID);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println();
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}


void mqttCallback(char* topic, byte* payload, unsigned int length) {
  String topicStr = topic;
  String value = "";
  for (int i = 0; i < length; i++) {
      value += (char)payload[i];
  }

  Serial.println("mqttCallback !");
  Serial.println(topicStr);
  Serial.println(value);

  if (topicStr == MQTT_TOPIC_CONTROL_ENABLED) {
    if (value.equals("1")) {
      setStepperEnabled(true);
    } else if (value.equals("0")) {
      setStepperEnabled(false);
    }
  }

  if (topicStr == MQTT_TOPIC_CONTROL_DIRECTION) {
    if (value.equals("1")) {
      setStepperDirection(DIRECTION_CLOSE);
    } else if (value.equals("0")) {
      setStepperDirection(DIRECTION_OPEN);
    }
  }

  if (topicStr == MQTT_TOPIC_CONTROL_STEPFOR) {
    int steps = value.toInt();
    stepFor(steps);
  }

  if (topicStr == MQTT_TOPIC_CONTROL_BLINDS) {
    if (value.equals("opened") && !isOpening) {
    // if (value.equals("opened")) {
      openBlinds();
    } else if (value.equals("closed") && !isClosing) {
    // } else if (value.equals("closed")) {
      closeBlinds();
    }
  }

  if (topicStr == MQTT_TOPIC_CONTROL_MODE_OPEN) {
    MODE_OPEN = value.toInt();
    saveToEeprom();
  }
  if (topicStr == MQTT_TOPIC_CONTROL_MODE_CLOSE) {
    MODE_CLOSE = value.toInt();
    saveToEeprom();
  }
  if (topicStr == MQTT_TOPIC_CONTROL_DELAY_OPEN) {
    DELAY_OPEN = value.toInt();
    saveToEeprom();
  }
  if (topicStr == MQTT_TOPIC_CONTROL_DELAY_CLOSE) {
    DELAY_CLOSE = value.toInt();
    saveToEeprom();
  }
  if (topicStr == MQTT_TOPIC_CONTROL_STEPS_VERTICAL) {
    STEPS_VERTICAL = value.toInt();
    saveToEeprom();
  }
}

void mqttReconnect() {
  while (!mqttClient.connected()) {
    Serial.print("Attempting MQTT connection...");

    // Attempt to connect
    if (mqttClient.connect(MQTT_CLIENT_ID, MQTT_USER, MQTT_PASSWORD, MQTT_TOPIC_STATUS, 1, true, "disconnected", false)) {
     Serial.println("connected");

      // Once connected, publish an announcement...
      mqttClient.publish(MQTT_TOPIC_STATUS, "connected", true);
    } else {
      Serial.print("failed, rc=");
      Serial.print(mqttClient.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }
}

void mqttPublish1(char *topic, int payload) {
  // Serial.print(topic);
  // Serial.print(": ");
  // Serial.println(payload);

  mqttClient.publish(topic, String(payload).c_str(), true);
}

void mqttPublish(char *topic, String payload) {
  // Serial.print(topic);
  // Serial.print(": ");
  // Serial.println(payload);

  mqttClient.publish(topic, payload.c_str(), true);
}


/**
* EEPROM HELPERS
*/

void loadFromEeprom() {
  EEPROM.begin(24);

  //Read data from eeprom
  int magicNumber;
  int modeOpen;
  int modeClose;
  int delayOpen;
  int delayClose;
  int stepsVertical;

  EEPROM.get(0, modeOpen);
  EEPROM.get(4, modeClose);
  EEPROM.get(8, delayOpen);
  EEPROM.get(12, delayClose);
  EEPROM.get(16, stepsVertical);
  EEPROM.get(20, magicNumber);
  EEPROM.end();

  if (magicNumber == EEPROM_MAGIC_NUMBER) {
    Serial.print("Successfully loaded config from eeprom");
    MODE_OPEN = modeOpen;
    MODE_CLOSE = modeClose;
    DELAY_OPEN = delayOpen;
    DELAY_CLOSE = delayClose;
    STEPS_VERTICAL = stepsVertical;
  } else {
    Serial.print("EEPROM MAGIC NUMBER INCORRECT: ");
    Serial.print(magicNumber);
    Serial.print(" != ");
    Serial.println(EEPROM_MAGIC_NUMBER);
    Serial.print("Keeping default step config!");
  }

  mqttPublish1(MQTT_TOPIC_MODE_OPEN, MODE_OPEN);
  mqttPublish1(MQTT_TOPIC_MODE_CLOSE, MODE_CLOSE);
  mqttPublish1(MQTT_TOPIC_DELAY_OPEN, DELAY_OPEN);
  mqttPublish1(MQTT_TOPIC_DELAY_CLOSE, DELAY_CLOSE);
  mqttPublish1(MQTT_TOPIC_STEPS_VERTICAL, STEPS_VERTICAL);
}

void saveToEeprom() {
  EEPROM.begin(24);

  EEPROM.put(0, MODE_OPEN);
  EEPROM.put(4, MODE_CLOSE);
  EEPROM.put(8, DELAY_OPEN);
  EEPROM.put(12, DELAY_CLOSE);
  EEPROM.put(16, STEPS_VERTICAL);
  EEPROM.put(20, EEPROM_MAGIC_NUMBER);
  EEPROM.commit();
  EEPROM.end();

  mqttPublish1(MQTT_TOPIC_MODE_OPEN, MODE_OPEN);
  mqttPublish1(MQTT_TOPIC_MODE_CLOSE, MODE_CLOSE);
  mqttPublish1(MQTT_TOPIC_DELAY_OPEN, DELAY_OPEN);
  mqttPublish1(MQTT_TOPIC_DELAY_CLOSE, DELAY_CLOSE);
  mqttPublish1(MQTT_TOPIC_STEPS_VERTICAL, STEPS_VERTICAL);
}


[CECG_trans_Logo]THANX
Mitch Geier
President
Computer Emergency & Consulting Group, LLC.
***@***.******@***.***>
609-758-1111 Ext 1

Privileged-Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer do not consent to Internet email for messages of this kind.

The sender believes that this E-mail and any attachments were free of any virus, worm, Trojan horse, and/or malicious code when sent. This message and its attachments could have been infected during  transmission. By reading the message and opening any attachments, the recipient accepts full responsibility for taking protective and remedial action about viruses and other defects. CECG LLC. and Mitch Geier are not liable for any loss or damage arising in any way from this message or its attachments.
P Please consider the environment before printing this email.
